apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u8bu7co2n-python 
  janus-idp.io/tekton: u8bu7co2n-python
  backstage.io/kubernetes-id: u8bu7co2n-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u8bu7co2n-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  